Account:
    Username: 
    Password: 
Files:
    Cache: /config/cache.json
    XMLTV: /config/xml.xml
Options:
    Poster Aspect: 2x3
    Schedule Days: 7
    Subtitle into Description: false
    Insert credits tag into XML file: true
    Local Images Cache: true
    Images Path: /data/images
    Internal HTTP server: false
    Hostname: localhost:9090
    Proxy Images: false
    Rating:
        Insert rating tag into XML file: true
        Maximum rating entries. 0 for all entries: 1
        Preferred countries. ISO 3166-1 alpha-3 country code. Leave empty for all systems:
          - USA
        Use country code as rating system: false
    Show download errors from Schedules Direct in the log: false
Station:
  - Name: HBO
    ID: "19548"
    Lineup: USA-IL67050-X
# Keep adding channels as needed
